### ISSUE TITLE
This Package keeps Breaking my App 

### ISSUE THREAD

**Issue by sheggietyn** [OrthoHQ/react-native-ortho#7]
Says: 

internalError Metro has encountered an error while trying to resolve module 'react-native-ortho'

**Comment by just1and0** [comment]
can you try installing react-native-webview ?

**Comment by sheggietyn** [comment]
i have web view already sir

**Comment by just1and0** [comment]
I just released V0.2.5 please try it out and confirm it works fine.

**Comment by just1and0** [comment]
I can confirm V0.2.5 works fine, I am going to close this issue.
