### ISSUE TITLE
Package Breaking 

### ISSUE THREAD

**Issue by sheggietyn** [OrthoHQ/react-native-ortho#8]
Still Getting the Same issue even after upgrading to the latest version and rebuilding my App 

InternalError Metro has encountered an error while trying to resolve module react-native-ortho

**Comment by just1and0** [comment]
Are you free for a call @sheggietyn ? we can sync now. Send me an invite just1and0@tryortho.co

**Comment by sheggietyn** [comment]
Zoom Call bro ?

**Comment by just1and0** [comment]
sure

**Comment by sheggietyn** [comment]
Zoom link sent bro .. check your mail

**Comment by just1and0** [comment]
I am in the waiting room.

**Comment by just1and0** [comment]
@sheggietyn can you join here https://meet.google.com/nsw-pmvm-ebk

**Comment by sheggietyn** [comment]
bro i have upgraded it again and rebuilt and it not showing the error again 

yarn add react-native-ortho@0.2.5

But the issue is it not even loading at all now 

The Screen I placed it on is just black with I think suppose to load the payment gateway instantly

**Comment by just1and0** [comment]
@sheggietyn and I were able to get on a call and resolve this, apparently he wrapped the component in a Modal which is not suppose to be done as the package already uses the modal.

by removing the modal it worked fine. I will close this out now.
